import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { basename, extname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { serveStatic } from "@hono/node-server/serve-static";
import { Hono } from "hono";

import type { ProviderAdapter } from "@openartifact/core";

import { loadConfig, ActiveConfig, type ServerConfig } from "./config";
import { defaultSnapshotRoot } from "./agent/runtime";
import { MemoryRepository, type Repository } from "./db";
import { createChatRouter } from "./routes/chat";
import { createConversationsRouter } from "./routes/conversations";
import { createSettingsRouter } from "./routes/settings";
import {
  generateSessionToken,
  loopbackGuard,
  sessionCookieValue,
  sessionTokenGuard,
} from "./security";

const SERVER_NAME = "open-artifact";
const SERVER_VERSION = "0.1.0";
const VITE_DEV_ORIGIN = "http://127.0.0.1:5173";

/**
 * The built web client lives in `apps/web/dist`; resolve it relative to this
 * file so the path works both from `src/` (tsx) and from `dist/` (tsc output).
 */
const WEB_DIST = fileURLToPath(new URL("../../web/dist/", import.meta.url));

/**
 * Vendored sandbox dependencies (§6 / §12.7): generated by `scripts/vendor.mjs`
 * into `apps/web/public/vendor/` and copied into `apps/web/dist/vendor/` by the
 * Vite build. Served with `Access-Control-Allow-Origin: *` because the artifact
 * iframe has an opaque origin. Dev reads `public/`, prod reads `dist/`.
 */
const WEB_VENDOR_DEV = fileURLToPath(new URL("../../web/public/vendor/", import.meta.url));
const WEB_VENDOR_PROD = fileURLToPath(new URL("../../web/dist/vendor/", import.meta.url));

const VENDOR_CONTENT_TYPES: Record<string, string> = {
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
};

export interface CreateAppOptions {
  /** Validated server config; defaults to {@link loadConfig} of the live env. */
  config?: ServerConfig;
  /** Random per-startup session token; generated when omitted (§9). */
  sessionToken?: string;
  /** Provider override for the chat routes (tests inject a tuned fake). */
  providerFactory?: () => ProviderAdapter;
  /** Persistence store; defaults to an in-memory store for tests/dev. */
  repository?: Repository;
  /** Mutable live config; defaults to a new {@link ActiveConfig} over `config`. */
  activeConfig?: ActiveConfig;
  /** Snapshot storage root for pre-mutation snapshots (§8); defaults to the home dir. */
  snapshotRoot?: string;
}

export function createApp(options: CreateAppOptions = {}): Hono {
  const config = options.config ?? loadConfig();
  const sessionToken = options.sessionToken ?? generateSessionToken();
  const activeConfig = options.activeConfig ?? new ActiveConfig(config);
  const repository = options.repository ?? new MemoryRepository();
  const snapshotRoot = options.snapshotRoot ?? defaultSnapshotRoot();

  const app = new Hono();

  app.get("/health", (c) =>
    c.json({ ok: true, name: SERVER_NAME, version: SERVER_VERSION }),
  );

  // Local-server security (§9): reject DNS-rebinding hosts and foreign origins.
  app.use("/api/*", loopbackGuard());

  // Bootstrap the session cookie and report the public config. Token-exempt so
  // the client can always call it first to receive the cookie.
  app.get("/api/session", (c) => {
    const live = activeConfig.get();
    c.header("Set-Cookie", sessionCookieValue(sessionToken));
    return c.json({
      ok: true,
      approvalMode: live.approvalMode,
      fakeProvider: live.fakeProvider,
      provider: live.provider,
    });
  });

  // Everything else under /api requires the session token.
  app.use("/api/*", sessionTokenGuard(sessionToken));

  app.route(
    "/api/chat",
    createChatRouter({
      activeConfig,
      repository,
      providerFactory: options.providerFactory,
      snapshotRoot,
    }),
  );

  app.route(
    "/api/conversations",
    createConversationsRouter({
      repository,
      workspaceRoot: activeConfig.get().workspaceRoot,
      snapshotRoot,
    }),
  );

  app.route("/api/settings", createSettingsRouter({ activeConfig, repository }));

  // Vendored sandbox ESM, registered before the dev proxy / prod static handler
  // so `/vendor/*` is always served from this origin with CORS.
  const isProduction = process.env.NODE_ENV === "production";
  const vendorDir = isProduction ? WEB_VENDOR_PROD : WEB_VENDOR_DEV;
  app.get("/vendor/:name", async (c) => {
    const name = c.req.param("name");
    // Only plain file names; reject dot-dot segments outright.
    if (!/^[\w.-]+$/.test(name) || name.includes("..")) {
      return c.text("Not found", 404);
    }
    const file = join(vendorDir, basename(name));
    if (!existsSync(file)) {
      return c.text("Not found", 404);
    }
    const type = VENDOR_CONTENT_TYPES[extname(name).toLowerCase()] ?? "application/octet-stream";
    return c.body(await readFile(file), 200, {
      "Content-Type": type,
      "Access-Control-Allow-Origin": "*",
    });
  });

  const webIndex = join(WEB_DIST, "index.html");
  const serveWebBuild = isProduction && existsSync(webIndex);

  if (serveWebBuild) {
    app.use("*", serveStatic({ root: WEB_DIST }));
    // SPA fallback: serve index.html for any client-side route.
    app.get("*", async (c) => c.html(await readFile(webIndex, "utf-8")));
  } else {
    // Development: proxy everything to the Vite dev server.
    app.all("*", async (c) => {
      if (isProduction) {
        return c.text("Web build not found. Run `pnpm build` first.", 503);
      }
      const incoming = new URL(c.req.url);
      const target = new URL(incoming.pathname + incoming.search, VITE_DEV_ORIGIN);
      const headers = new Headers(c.req.raw.headers);
      headers.delete("host");
      headers.delete("connection");
      let upstream: Response;
      try {
        upstream = await fetch(target, {
          method: c.req.method,
          headers,
          body:
            c.req.method === "GET" || c.req.method === "HEAD"
              ? undefined
              : await c.req.raw.arrayBuffer(),
          redirect: "manual",
        });
      } catch {
        return c.text("Vite dev server is not running. Run `pnpm dev` from the repo root.", 502);
      }
      return new Response(upstream.body, {
        status: upstream.status,
        statusText: upstream.statusText,
        headers: upstream.headers,
      });
    });
  }

  return app;
}
